[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
  "-Crelocation-model=static",
]

[profile.dev]
panic = "abort"
split-debuginfo = "packed"

[profile.release]
panic = "abort"
strip = "symbols"
opt-level = "z"
lto = "fat"

[env]
CC = "clang"