[package]
name = "picolibc-sys"
version.workspace = true
edition.workspace = true

[dependencies]

[build-dependencies]
picomeson = "0.1.2"
anyhow = "1.0"
tempfile = "3.22"
cc = { version = "1.2.37", features = ["parallel"] }
bindgen = { version = "0.72.1" }
glob = "0.3.3"